const menu = [
  {
    id: 1,
    title: "Delicious Pizza",
    category: "Pizza",
    price: 100,
    img: "images/f1.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
  {
    id: 2,
    title: "Delicious Burger",
    category: "Burger",
    price: 100,
    img: "images/f2.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
  {
    id: 3,
    title: "Delicious Pizza",
    category: "Pizza",
    price: 100,
    img: "images/f3.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
  {
    id: 4,
    title: "Delicious Pasta",
    category: "Pasta",
    price: 10,
    img: "images/f4.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
  {
    id: 5,
    title: "French Fries",
    category: "Fries",
    price: 150,
    img: "images/f5.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
  {
    id: 6,
    title: "Delicious Pizza",
    category: "Pizza",
    price: 150,
    img: "images/f6.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque `,
  },
  {
    id: 7,
    title: "Tasty Burger",
    category: "Burger",
    price: 150,
    img: "images/f7.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
  {
    id: 8,
    title: "Tasty Burger",
    category: "Burger",
    price: 150,
    img: "images/f8.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
  {
    id: 9,
    title: "Delicious Pasta",
    category: "Pasta",
    price: 150,
    img: "images/f9.png",
    desc: `Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque`,
  },
];
export default menu;
